export interface movie {
    id: string,
    name: string,
    year: number,
    description: string,
    runtime: number,
    genres: any[],
    parentRating: string,
    imdbRating: number,
    yourRating: number,
    link: string,
    poster: string,
    youtubeTrailer: string,
    director: string,
    stars: string,
    userId: any,
    medialistIds: number[],
    xRefMoviesMedialists: any[],
}